### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by sm-joe** [PaloAltoNetworks/pcs-cwp-defender-updater#1]
## Describe the problem
Documentation is not clear for the implementation.

## Suggested fix
Pls create step-by-step instructions to be able to implement is successfully.

**Comment by jfmontufar** [comment]
Hi @sm-joe 
Sorry that I noticed late. Please review the docs to see if it fits your needs.

**Comment by jfmontufar** [comment]
No further requirement to update the documentation
